### PR TITLE
Add Makefile

### PR DESCRIPTION
**Pull request by karpet**
```bash
% make deps   # install dependencies
% make venv   # setup env
% make run    # run the dev server
% make test   # run the test suite
```

### CODE REVIEW

**Comment by karpet** [comment]
@JoshuaMitchell if this looks ok to you, feel free to click the green "Squash and merge" button.

**Comment by JoshuaMitchell** [comment]
I am largely unfamiliar with makefiles... shouldn't there actually be bash commands in there for the proposed make commands?

**Comment by karpet** [comment]
If you look at https://github.com/BlueprintKansas/ksvotes.org/pull/23/files you can see the Makefile itself and the targets/commands.

**Comment by JoshuaMitchell** [comment]
Got it.  Thanks!

**Pull request merged**
