### PR TITLE
Special messaging if SOS VV site fails

### PR DESCRIPTION
**Pull request by karpet**
screen shot 2018-09-09 at 8 42 34 pm

### CODE REVIEW

**Comment by karpet** [comment]
@katherinepdavis are the action buttons correct in this case? Should we change the language at all?

**Comment by katherinepdavis** [comment]
I think it's good as is.

**Comment by karpet** [comment]
it just needed to be merged and deployed first

**Comment by katherinepdavis** [comment]
I'm still not getting this message

**Comment by karpet** [comment]
I broke it when I implemented #344 

fixed in #383

**Pull request merged**
